Python Data Science Handbook by Jake VanderPlas 
[Link](https://jakevdp.github.io/PythonDataScienceHandbook/)

# Chapter: Data Manipulation with Pandas

In [ ]:
# to display all the contents of the pandas namespace, you can type
pd.<TAB>

# to display Pandas's built-in documentation, you can use this:
pd?

# Introducting Pandas Objects

## The Pandas Series Object


In [1]:
import numpy as np
import pandas as pd

In [3]:
# a pandas series is a 1d array of indexed data
# can be created from a list or array as follows
data = pd.Series([0.25, 0.5, 0.75, 1.0])

In [4]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
# The index is an array-like object of type pd.Index
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
# data can be accessed by associated index via familiar python square-bracket notation
data[1]

0.5

In [8]:
data[1:3]

1    0.50
2    0.75
dtype: float64

### [series] as a generalised NumPy array

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index = ['a', 'b', 'c', 'd' ])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [3]:
data['b']

0.5

In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index = [2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [5]:
data[5]

0.5

### Series as specialised dictionary

- Pandas [series] -> like a specialised python dictionary
- dictionary is a sgtructure which maps arbitrary keys to a set of values
- a [series] is a structure which maps typed keys to a set of values

In [4]:
population_dict = {'California': 38332521,
                   'Texas':      26448193,
                   'New York':   19651127,
                   'Florida':    19552860,
                   'Illinois':   12882135 }

population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

- a series will be created where the index is drawn from the sorted keys. 

In [7]:
population['California']

38332521

In [8]:
# series (unlike dictoinary) supports array-style operations like slicing
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

### Consructing Series objects

- constructing pandas series from scratch
- pd.Series(data, index=index)
- index optional

In [9]:
#data can be a list or NumPy array, index defaults to integer seq
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [10]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [11]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

## The Pandas DataFrame Object

- [Series] is an analog of a 1d array
- [dataframe] is an analog of 2d array
- dataframe a sequence of aligned series obj (alighned = share same index)


In [2]:
import pandas as pd

In [3]:
# construct a new series

area_dict = {'California': 423967, 'Texas': 695662,
             'New York': 695662,   'Florida': 170312,
             'Illinois': 149995 }
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      695662
Florida       170312
Illinois      149995
dtype: int64

In [5]:
# add population
# create a 2d object using dictionary

states = pd.DataFrame({'popluation': population,
                       'area': area })

states

popluation    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  695662
Florida       19552860  170312
Illinois      12882135  149995

In [6]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [7]:
states.columns

Index(['popluation', 'area'], dtype='object')

Dataframe as a specialized dictionary

In [8]:
#dataframe specialised dictionary
# dict maps a key to a value
# dataframe maps a col name to a series of col data

states['area']

California    423967
Texas         695662
New York      695662
Florida       170312
Illinois      149995
Name: area, dtype: int64

Constructing dataframe objects

- pandas dataframe can be constructed in a variety of ways
- examples below

from  a single Series object

In [9]:
## 

# a df is a collection of Series objects
# a single col dataframe can be constructed from a single Series

pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

from a list of dicts

In [10]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [12]:
pd.DataFrame([{'a':1, 'b':2}, {'b':3, 'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

From a dictionary of series objects

In [13]:
pd.DataFrame({'population': population,
               'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  695662
Florida       19552860  170312
Illinois      12882135  149995

In [15]:
import numpy as np

From a 2d numpy array

In [16]:
pd.DataFrame(np.random.rand(3,2),
            columns=['foo','bar'],
            index=['a','b','c'])

foo       bar
a  0.145524  0.624846
b  0.985889  0.485589
c  0.007081  0.555367

from a numpy structured array

In [17]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [18]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

# the pandas index object

In [19]:
# construct an index from a list of integers
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

index as immutable
array

In [20]:
# can use standard indexing to retrieve values or slices
ind[1]

3

In [21]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [22]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [23]:
#indices cant be modified via normal means
ind[1] = 1

TypeError: Index does not support mutable operations

index as ordered set

In [24]:
indA = pd.Index([1,2,3,4,5])
indB = pd.Index([9,2,3,4,8])

In [25]:
indA & indB #intersection

/tmp/ipykernel_431/1860335538.py:1: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  indA & indB #intersection


Int64Index([2, 3, 4], dtype='int64')

In [26]:
indA | indB #union

/tmp/ipykernel_431/2837849747.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  indA | indB #union


Int64Index([1, 2, 3, 4, 5, 8, 9], dtype='int64')

In [27]:
indA ^ indB #symmetric difference

/tmp/ipykernel_431/2613523914.py:1: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead.
  indA ^ indB #symmetric difference


Int64Index([1, 5, 8, 9], dtype='int64')

# Data indexing and selection

https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html

Data selection in Series

- series as a dictionary

In [28]:
# mapped keys to a collection of values
import pandas as pd

data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = ['a', 'b', 'c', 'd'])

data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [29]:
data['b']

0.5

In [30]:
'a' in data

True

In [31]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [32]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [33]:
# can add/extend series with new values

data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

series as a 1d array


In [34]:
#slicing by explicit index

data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [35]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [36]:
#masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [37]:
# fancy indexing
data[['a',  'e']]

a    0.25
e    1.25
dtype: float64

indexers: loc, iloc, ix

In [38]:
data = pd.Series(['s', 'b', 'f'], index = [1,3,5])

In [39]:
data

1    s
3    b
5    f
dtype: object

In [40]:
#explicit index when indexing
data[1]

's'

In [41]:
#implicit index when slicing
data[1:3]

3    b
5    f
dtype: object

In [42]:
# loc attributed allows indexing and slicing ref explicit index
data.loc[1]

's'

In [43]:
data.loc[1:3]

1    s
3    b
dtype: object

In [44]:
data.iloc[1]

'b'

In [45]:
data.iloc[1:3]

3    b
5    f
dtype: object

Data selection in dataframe

In [46]:
#data frame as a dictionary

In [47]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [48]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [49]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [50]:
data.area is data['area']

True

In [51]:
data.pop is data['pop']

False

In particular, you should avoid the temptation to try column assignment via attribute (i.e., use data['pop'] = z rather than data.pop = z).

In [53]:
data['density'] = data['pop'] / data['area']

In [54]:
data['density']

California     90.413926
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
Name: density, dtype: float64

dataframe as 2d array

In [55]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [56]:
#transpose
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [57]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [58]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [60]:
#for array style indexing use iloc
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [61]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [62]:
# The ix indexer allows a hybrid of these two approaches:

data.ix[:3, :'pop']

AttributeError: 'DataFrame' object has no attribute 'ix'

In [63]:
# the loc indexer we can combine masking and fancy indexing as in the following:

data.loc[data.density > 100, ['pop',    'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [64]:
# modify values
data.iloc[0,2] = 90

In [65]:
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

- indexing refers to colmns
- slicing refers to rows

In [67]:

data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [68]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [69]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

Operating on data in pandas

- ufuncs: index preservation
- numpy ufunc will work on any pandas series and dataframe obj

In [70]:
import pandas as pd
import numpy as np

In [71]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))

In [72]:
ser

0    6
1    3
2    7
3    4
dtype: int64

In [73]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),
                    columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

now if apply numpy ufunc on either above objects, results will be another pandas object wth the indices predserved


In [74]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [75]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

ufuncs  index   alignment
- index alignment in series

In [76]:
# example combining two different data sources
# find top 3 us states by area
# find top 3 us states by populaton

In [77]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')

population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [78]:
# calc population density

population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [79]:
# only have results for overlapping indices
area.index | population.index

/tmp/ipykernel_431/1002832183.py:2: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  area.index | population.index


Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [80]:
# anything thats NaN (not a number) due to index mismatching

In [81]:
A = pd.Series([2, 4, 6], index =[0,1,2])
B = pd.Series([1, 3, 5], index =[1,2,3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [82]:
# modify fill value

A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

- index alignment in dataframe

In [86]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                    columns=list('AB'))

A

A   B
0  19   2
1   4  18

In [85]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [87]:
A + B

A     B   C
0  19.0   6.0 NaN
1  12.0  23.0 NaN
2   NaN   NaN NaN

In [89]:
# fill any missing values with the mean of all values in A
# compute by first stacking the rows of A
fill = A.stack().mean()
A.add(B, fill_value=fill)

A      B      C
0  19.00   6.00  19.75
1  12.00  23.00  10.75
2  12.75  19.75  16.75


Python Operator	Pandas Method(s)
+	add()
-	sub(), subtract()
*	mul(), multiply()
/	truediv(), div(), divide()
//	floordiv()
%	mod()
**	pow()

Ufuncs: Operations Between DataFrame and Series

In [90]:
A = rng.randint(10, size=(3,4))
A

array([[6, 4, 8, 6],
       [1, 3, 8, 1],
       [9, 8, 9, 4]])

In [91]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-5, -1,  0, -5],
       [ 3,  4,  1, -2]])

In [92]:
# subtraction applied row wise
df = pd.DataFrame(A, columns = list('QRST'))

df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -5 -1  0 -5
2  3  4  1 -2

In [93]:
# to operate col wise, specify axis

df.subtract(df['R'], axis = 0)

Q  R  S  T
0  2  0  4  2
1 -2  0  5 -2
2  1  0  1 -4

In [94]:
halfrow = df.iloc[0, ::2]
halfrow

Q    6
S    8
Name: 0, dtype: int64

In [95]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -5.0 NaN  0.0 NaN
2  3.0 NaN  1.0 NaN

# Handling missing data

https://jakevdp.github.io/PythonDataScienceHandbook/03.04-missing-values.html

- built in daratools for missing data
- Missing data detection:
    - Masking approach: globally indicate missing values. Mask may be a separate boolean array,
    - Senintel value: indicate missing entry could be some data-specific convention, such as indicating a missing integer value with -9999 or some rare bit pattern, or it could be a more global convention, such as indicating a missing floating-point value with NaN (Not a Number), a special value which is part of the IEEE floating-point specification.

- Trade-offs:
    - Boolean masl - additional storage and computation
    - Sentinel - reduces range of valid values that can be represented, may require logic in CPU and GPU arithmetic. NaN not available for all data types.
    - R uses reserved bit patterns within each data type as sentinel values to indicate missing data

Missing data in pandas
- Relies on NumPy package (which doenst have a built in notion of NA values for non floating point data types)

- R has a single integer type and 4 basic data types, but NumPy supports 14 basic integer types
- To reserve a specific bit pattern in all NumPy data types would lead to lots of overhead in special-case operations for various types
- NumPy does support masked arrays which have a separate Boolean mask array attached. But overhead in storage, computation and code maintenance means unattractive
- Pandas uses sentinels for missing data
- Uses NaN (special floating point value) and None obj

Pythonic missing data
- First sentinel value used by Pandas is [None]
- only used in arrays with type 'object'

In [96]:
import pandas as pd
import numpy as np

In [97]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [98]:

# dtype = object, means best common type representation for contents were objects

In [100]:
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
30.3 ms ± 511 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
462 µs ± 777 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)



- use of obj lead to errors when performing aggregations (like sum, min) when you have a None value

In [102]:
vals1.sum()
# addition of integer and NONE is undefined

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

Missing numerical data
- NaN (Not a number) is a special floating point value recog by all systems using standard IEEE floating point representation